name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: app/tests/e2e/package.json
    
    - name: Install dependencies
      run: |
        cd app/tests/e2e
        npm ci
    
    - name: Install Playwright browsers
      run: |
        cd app/tests/e2e
        npx playwright install chromium --with-deps
    
    - name: Start Docker containers
      run: |
        docker-compose build
        docker-compose up -d
    
    - name: Wait for application to start
      run: |
        echo "Waiting for application to start..."
        sleep 10
        
        # Check if the application is accessible
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080
    
    - name: Run Playwright tests
      run: |
        cd app/tests/e2e
        npx playwright test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: app/tests/e2e/test-results/
        retention-days: 30
